# To use the MeowCop gem.
inherit_gem:
  meowcop:
    - config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: true
  Max: 100

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
